services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio-nestjs
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
