export const SEQUELIZE = 'SEQUELIZE';
export const CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY';
export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const TRANSACTION_ACCOUNT_REPOSITORY = 'TRANSACTION_ACCOUNT_REPOSITORY';
